package jopa.types;

public enum JOPAGLType {
	JOPA_BOOL,
	JOPA_INT,
	JOPA_UINT,
	JOPA_FLOAT,
	JOPA_BOOL_VECTOR_2,
	JOPA_INT_VECTOR_2,
	JOPA_UIUNT_VECTOR_2,
	JOPA_FLOAT_VECTOR_2,
	JOPA_BOOL_VECTOR_3,
	JOPA_INT_VECTOR_3,
	JOPA_UIUNT_VECTOR_3,
	JOPA_FLOAT_VECTOR_3,
	JOPA_BOOL_VECTOR_4,
	JOPA_INT_VECTOR_4,
	JOPA_UIUNT_VECTOR_4,
	JOPA_FLOAT_VECTOR_4,
	// matrices
}